Repository kaspanet/kaspad, pull requests merged in 2021-01, with the labels that each got.

#1349 Save and expose the database in TestConsensus
  domain/consensus/factory.go
  domain/consensus/model/testapi/test_consensus.go
  domain/consensus/test_consensus.go
  domain/consensus/test_consensus_getters.go
Labels: tests

#1351 Delete from the tips list blocks that are in Pruning's Anticone
  domain/consensus/processes/pruningmanager/pruningmanager.go
Labels: bug, consensus

#1344 Update the max block size and mass constants to reasonable values
  domain/dagconfig/consensus_defaults.go
Labels: breaking-consensus

#1359 Reverse ghostdag tie break direction
  domain/consensus/model/externalapi/hash.go
  domain/consensus/processes/dagtraversalmanager/window_test.go
  domain/consensus/processes/ghostdag2/ghostdagimpl.go
  domain/consensus/processes/ghostdagmanager/ghostdag_test.go
  domain/consensus/processes/pruningmanager/pruning_test.go
  domain/consensus/testdata/dags/dag1.json
  domain/consensus/testdata/dags/dag2.json
Labels: breaking-consensus, breaking-database, consensus

#1360 Add script pubkey version to signature hash
  domain/consensus/database/serialization/blockheader.go
  domain/consensus/database/serialization/transaction.go
  domain/consensus/database/serialization/utxo_entry.go
  domain/consensus/utils/txscript/engine.go
  domain/consensus/utils/txscript/opcode.go
  domain/consensus/utils/txscript/script.go
  infrastructure/network/netadapter/server/grpcserver/protowire/p2p_header.go
  infrastructure/network/netadapter/server/grpcserver/protowire/p2p_transaction.go
  infrastructure/network/netadapter/server/grpcserver/protowire/rpc_get_block.go
  infrastructure/network/netadapter/server/grpcserver/protowire/rpc_submit_transaction.go
Labels: breaking-consensus, breaking-database, consensus

#1364 Update devnet genesis with older timestamp
  domain/consensus/processes/dagtraversalmanager/window_test.go
  domain/dagconfig/genesis.go
Labels: breaking-database

#1374 Increase log files sizes
  infrastructure/logger/logger.go
Labels: logs

#1386 Optimize block locator using finality store
  domain/consensus/factory.go
  domain/consensus/processes/dagtraversalmanager/dagtraversalmanager.go
  domain/consensus/processes/syncmanager/blocklocator.go
Labels: optimization, p2p

#1406 Log the networks hashrate
  app/rpc/rpccontext/verbosedata.go
  cmd/kaspaminer/mineloop.go
  domain/consensus/factory.go
  domain/consensus/model/pow/pow.go
  domain/consensus/processes/blockprocessor/blockprocessor.go
  domain/consensus/processes/blockprocessor/validateandinsertblock.go
  domain/consensus/processes/blockvalidator/blockvalidator.go
  domain/consensus/processes/blockvalidator/proof_of_work.go
  domain/consensus/processes/blockvalidator/proof_of_work_test.go
  domain/consensus/processes/difficultymanager/blockwindow.go
  domain/consensus/processes/difficultymanager/difficultymanager.go
  domain/consensus/processes/difficultymanager/difficultymanager_test.go
  domain/consensus/processes/ghostdag2/ghostdagimpl.go
  domain/consensus/processes/ghostdagmanager/ghostdag.go
  domain/consensus/processes/ghostdagmanager/ghostdag_test.go
  domain/miningmanager/blocktemplatebuilder/blocktemplatebuilder.go
  testing/integration/mining_test.go
  util/difficulty/difficulty.go
  util/difficulty/difficulty_test.go
  util/example_test.go
  util/math/min_test.go
  util/math_test.go
Labels: logs

#1414 Remove code coverage patch check and make it informational
  .codecov.yml
Labels: CI, tests

#1432 Restructure database to prevent double-slashes in keys, causing bugs in cursors
  domain/consensus/consensus.go
  domain/consensus/database/bucket.go
  domain/consensus/database/errors.go
  domain/consensus/database/key.go
  domain/consensus/datastructures/acceptancedatastore/acceptancedatastore.go
  domain/consensus/datastructures/blockheaderstore/blockheaderstore.go
  domain/consensus/datastructures/blockrelationstore/blockrelationstore.go
  domain/consensus/datastructures/blockstatusstore/blockstatusstore.go
  domain/consensus/datastructures/blockstore/blockstore.go
  domain/consensus/datastructures/consensusstatestore/tips.go
  domain/consensus/datastructures/consensusstatestore/utxo.go
  domain/consensus/datastructures/consensusstatestore/virtual_diff_parents.go
  domain/consensus/datastructures/finalitystore/finality_store.go
  domain/consensus/datastructures/ghostdagdatastore/ghostdagdatastore.go
  domain/consensus/datastructures/headersselectedchainstore/headersselectedchainstore.go
  domain/consensus/datastructures/headersselectedtipstore/headertipsstore.go
  domain/consensus/datastructures/multisetstore/multisetstore.go
  domain/consensus/datastructures/pruningstore/pruningstore.go
  domain/consensus/datastructures/reachabilitydatastore/reachabilitydatastore.go
  domain/consensus/datastructures/utxodiffstore/utxodiffstore.go
  domain/consensus/processes/blockprocessor/validateandinsertpruningpoint_test.go
  domain/consensus/processes/finalitymanager/finality_manager.go
  domain/consensus/processes/reachabilitymanager/fetch.go
  domain/consensus/processes/syncmanager/blocklocator.go
  domain/consensus/utils/dbkeys/dbkeys.go
  infrastructure/db/database/common_test.go
  infrastructure/db/database/cursor_test.go
  infrastructure/db/database/database_test.go
  infrastructure/db/database/keys.go
  infrastructure/db/database/keys_test.go
  infrastructure/db/database/ldb/cursor_test.go
  infrastructure/db/database/ldb/leveldb_test.go
  infrastructure/db/database/ldb/transaction_test.go
  infrastructure/db/database/transaction_test.go
Labels: breaking-database

#1441 Remove accidental pointer indirection in dbKey
  domain/consensus/database/key.go
Labels: optimization

#1448 Add P2P/RPC name to the gRPC logs
  infrastructure/network/netadapter/server/grpcserver/grpc_server.go
  infrastructure/network/netadapter/server/grpcserver/p2pserver.go
  infrastructure/network/netadapter/server/grpcserver/rpcserver.go
Labels: logs

#1455 Fix 3 race conditions in kaspaminer
  cmd/kaspaminer/mineloop.go
Labels: bug, kaspaminer
