Repository kaspanet/kaspad, pull requests merged in 2021-02, with the labels that each got.

#1476 Prevent infinite ticker leaks in kaspaminer
  cmd/kaspaminer/mineloop.go
  infrastructure/network/connmanager/connmanager.go
Labels: bug, kaspaminer, optimization

#1474 Fix data races in ConnectionManager and flow tests
  app/protocol/flows/testing/handle_relay_invs_test.go
  infrastructure/network/connmanager/connmanager.go
Labels: tests

#1518 Limit stdout log level to info
  infrastructure/config/config.go
  infrastructure/config/sample-kaspad.conf
  infrastructure/config/sample_config.go
  infrastructure/logger/logger.go
  infrastructure/logger/logs.go
Labels: logs, optimization

#1520 Make RPC command GetBlocks prepend lowHash to return value and fix error when lowHash=highHash
  app/rpc/rpchandlers/get_blocks.go
  app/rpc/rpchandlers/get_blocks_test.go
  domain/consensus/processes/syncmanager/antipast.go
  domain/consensus/processes/syncmanager/syncmanager_test.go
Labels: RPC

#1533 Fix a data race in the block logger in tests
  domain/consensus/processes/blockprocessor/blocklogger/blocklogger.go
  domain/consensus/processes/blockprocessor/blockprocessor.go
  domain/consensus/processes/blockprocessor/validateandinsertblock.go
Labels: bug

#1534 Nightly run for go test race detector
  .github/workflows/go-race.yml
Labels: CI

#1545 Github Actions - Don't cancel the rest of the jobs if one failed
  .github/workflows/go-race.yml
  .github/workflows/go.yml
Labels: CI

#1550 Remove virtual diff parents
  domain/consensus/database/serialization/dbobjects.pb.go
  domain/consensus/database/serialization/dbobjects.proto
  domain/consensus/database/serialization/virtual_diff_parents.go
  domain/consensus/datastructures/consensusstatestore/consensusstatestore.go
  domain/consensus/datastructures/consensusstatestore/virtual_diff_parents.go
  domain/consensus/model/interface_datastructures_consensusstatestore.go
  domain/consensus/processes/consensusstatemanager/import_pruning_utxo_set.go
  domain/consensus/processes/consensusstatemanager/multisets.go
  domain/consensus/processes/consensusstatemanager/resolve_block_status.go
  domain/consensus/processes/consensusstatemanager/update_virtual.go
  domain/consensus/processes/consensusstatemanager/utxo_diffs.go
  domain/consensus/processes/pruningmanager/pruningmanager.go
Labels: breaking-database

#1557 Fix subnetworks FromString and disable reversal
  app/appmessage/domainconverters.go
  domain/consensus/model/externalapi/subnetworkid.go
  domain/consensus/utils/subnetworks/compare.go
  domain/consensus/utils/subnetworks/from_string.go
Labels: bug
